### PR TITLE
influx authentization

### PR DESCRIPTION
**Pull request by LukasVyhlidka**

### CODE REVIEW

**Comment by LukasVyhlidka** [comment]
Seems as this repo is not maintained by anyone, am I correct? :-/

**Comment by mman** [comment]
@LukasVyhlidka I am working on binging up the repository up to date by bumping up the necessary dependencies, I will take a look at your pull request and add ability to change username/password from the UI as well.

**Comment by mman** [comment]
This issue is addressed in https://github.com/victronenergy/venus-docker-grafana-images/pull/22, will probably be merged and released officially at some point in the future.

**Comment by mman** [comment]
Addressed in https://github.com/victronenergy/venus-influx-loader. Closing.

**Pull request closed without merging**
